DO $$ 
DECLARE
	mnth SMALLINT := (SELECT EXTRACT(MONTH FROM CURRENT_TIMESTAMP));
	yr SMALLINT := (SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP));


BEGIN
	EXECUTE format('
	CREATE TABLE IF NOT EXISTS complete%s%s (
		id VARCHAR(40) PRIMARY KEY,
		channelId VARCHAR(40) REFERENCES channel(id),
		recipient TEXT NOT NULL,
		subject TEXT NOT NULL,
		content TEXT NOT NULL,
		createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		expireOn TIMESTAMP NOT NULL,
		status VARCHAR(10) NOT NULL,
		attempts SMALLINT NOT NULL,
		priority SMALLINT NOT NULL,
		reference TEXT NOT NULL,
		UNIQUE(id)
	);', yr, mnth);
END $$;
