CREATE TABLE IF NOT EXISTS template (
	id VARCHAR(40) PRIMARY KEY,
	name TEXT NOT NULL,
	key TEXT NOT NULL,
	subject TEXT NOT NULL,
	body TEXT NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled BOOLEAN NOT NULL default(true),
	deleted BOOLEAN NOT NULL default(false),
	UNIQUE(id),
	UNIQUE(key)
);