CREATE TABLE IF NOT EXISTS otps (
	id SERIAL PRIMARY KEY,
	userid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	token FLOAT NOT NULL,
	expireddate TIMESTAMP NOT NULL,
	createdat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	verified BOOLEAN NOT NULL default(false),
	UNIQUE(id, userid),
	UNIQUE(token)
);
