CREATE TABLE IF NOT EXISTS gfuser (
	id BIGSERIAL PRIMARY KEY,
	relatedId INTEGER NOT NULL,
	email VARCHAR(50) NOT NULL,
	key VARCHAR(100) NOT NULL,
	createdBy BIGINT NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedBy BIGINT NOT NULL,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled BOOLEAN NOT NULL default(false),
	deleted BOOLEAN NOT NULL default(false),
	UNIQUE(email),
	UNIQUE(email, key)
);
