CREATE TABLE IF NOT EXISTS template (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	staticName VARCHAR(20) NOT NULL,
	subject VARCHAR(200) NOT NULL,
	body TEXT NOT NULL,
	paramsCount SMALLINT NOT NULL,
	createdBy BIGINT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedBy BIGINT NULL,
	updatedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled BOOLEAN NOT NULL default(true),
	deleted BOOLEAN NOT NULL default(false),
	UNIQUE(id),
	UNIQUE(staticName)
);