DO $$ 
DECLARE
	mnth SMALLINT := (SELECT EXTRACT(MONTH FROM CURRENT_TIMESTAMP));
	yr SMALLINT := (SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP));
BEGIN
	EXECUTE format('CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_queue_report ON queue%s%s USING BTREE(channelId, statusId);', yr, mnth);
END $$;
