DO $$ 
DECLARE
	mnth SMALLINT := (SELECT EXTRACT(MONTH FROM CURRENT_TIMESTAMP));
	yr SMALLINT := (SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP));
BEGIN
	EXECUTE format('CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_complete_fetch ON complete%s%s USING BTREE(channelId, statusId, attempts);', yr, mnth);
END $$;
