DO $$ 
DECLARE
	mnth SMALLINT := (SELECT EXTRACT(MONTH FROM CURRENT_TIMESTAMP));
	yr SMALLINT := (SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP));
BEGIN
	EXECUTE format('CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS idx_failed_id ON failed%s%s USING BTREE(id DESC);', yr, mnth);
END $$;
