CREATE TABLE IF NOT EXISTS dashboard (
	id BIGSERIAL,
	year INTEGER NOT NULL,
	month INTEGER NOT NULL,
	request INTEGER NOT NULL,
	staging INTEGER NOT NULL,
	queue INTEGER NOT NULL,
	complete INTEGER NOT NULL,
	failed INTEGER NOT NULL,
	PRIMARY KEY (id)
);