@hostname = 192.168.100.50
@port = 5002
@host = {{hostname}}:{{port}}
@contentType = application/json
@email = muthurimixphone@gmail.com
@clientid = 98590c398a254d2898838e1b17381575
@secret = ADRtjWLkttBbMQLpMADF

### Get Channel
# @name getChannel
GET https://{{hostname}}/notify/channel
Content-Type: {{contentType}}
email: {{email}}
clientid: {{clientid}}
secret: {{secret}}


### Update Channel
# @name updateChannel
PUT https://{{host}}/notify/channel
Content-Type: {{contentType}}
email: {{email}}
clientid: {{clientid}}
secret: {{secret}}

{
    "id": 2,
    "name": "email",
    "staticName": "email",
    "priority": 2
}