### dashboard
GET http://localhost:5002/notify/dashboard?year=2020&month=11
Content-Type: application/json
email: muthurimixphone@gmail.com
clientid: 98590c398a254d2898838e1b17381575
secret: ADRtjWLkttBbMQLpMADF

### report
GET http://localhost:5002/notify/report?table=complete&channel=2&year=2020&month=11&page=1
Content-Type: application/json
email: muthurimixphone@gmail.com
clientid: 98590c398a254d2898838e1b17381575
secret: ADRtjWLkttBbMQLpMADF
