@hostname = 127.0.0.1
@port = 5002
@host = {{hostname}}:{{port}}
@contentType = application/json
@email = muthurimixphone@gmail.com
@clientid = 98590c398a254d2898838e1b17381575
@secret = ADRtjWLkttBbMQLpMADF


### Get Template
# @name getTemplate
GET http://{{host}}/notify/template?page=1
Content-Type: {{contentType}}
email: {{email}}
clientid: {{clientid}}
secret: {{secret}}


### Add Template
# @name addTemplate
POST http://{{host}}/notify/template
Content-Type: {{contentType}}
email: {{email}}
clientid: {{clientid}}
secret: {{secret}}

{
	"name" : "Test",
	"staticName": "test",
	"subject": "Test",
	"body": "Dear Customer,\n\nThank you for contacting Respect Obituary. We have received your e-mail and our team will respond to you soon.\nPlease note our working hours are 0830 to 1630 (EAT) from Monday to Friday and 0900 to 1230 every last Saturday of the month.\nWe regret any delays in reply during non-working hours.\nServing you is our top priority.\n\nThank You.\n\n\n\nRegards,\nGreat Focus\n\n\n\n",
	"paramsCount": 0
}


### Edit Template
# @name editTemplate
PUT http://{{host}}/notify/template
Content-Type: {{contentType}}
email: {{email}}
clientid: {{clientid}}
secret: {{secret}}

{
    "id": 6,
    "name": "Test",
    "staticName": "test",
    "subject": "Test",
    "body": "test",
	"paramsCount": 0
}


### Delete Template
# @name deleteTemplate
DELETE  http://{{host}}/notify/template?id=7
Content-Type: {{contentType}}
email: {{email}}
clientid: {{clientid}}
secret: {{secret}}