### Get Template
GET http://localhost:5002/notify/template?page=1
Content-Type: application/json
email: muthurimixphone@gmail.com
clientid: 98590c398a254d2898838e1b17381575
secret: ADRtjWLkttBbMQLpMADF


### Add Template
POST http://localhost:5002/notify/template
Content-Type: application/json
email: muthurimixphone@gmail.com
clientid: 98590c398a254d2898838e1b17381575
secret: ADRtjWLkttBbMQLpMADF

{
	"name" : "Client Credentials",
	"staticName": "client_credentials",
	"subject": "Client Credentials",
	"body": "Hi, \nWe hereby notify you request to access API service has been granted. See below you credentials clientId:  $1, secret: $2 for login. Kindly share with is your experience with us, we would be glad to receive your feedback. \n\nThe Respect Team",
	"paramsCount": 2
}

### Edit Template
PUT http://localhost:5002/notify/template
Content-Type: application/json
email: muthurimixphone@gmail.com
clientid: 98590c398a254d2898838e1b17381575
secret: ADRtjWLkttBbMQLpMADF

{
    "id": 1,
    "name": "OTP",
    "staticName": "otp",
    "subject": "Please verify your registration",
    "body": "Hello, \\n\\n Thank you for registering and partnering with us. To complete the registration, enter the verification code.\\n\\n \u003cb\u003eVerification code: $1\u003c/b\u003e \\n\\n Thanks,\\n The Respect Team",
    "paramsCount": 1
}

### Edit Template
DELETE  http://localhost:5002/notify/template?id=4
Content-Type: application/json
email: muthurimixphone@gmail.com
clientid: 98590c398a254d2898838e1b17381575
secret: ADRtjWLkttBbMQLpMADF